In [1]:
import numpy as np
import pandas as pd

In [7]:
# Let's first load the data from excel file in our dataFrame(using read_excel rather than csv since file format is .xlsx)
df = pd.read_excel('../data/student_performance_dataset.xlsx')

In [8]:
df.shape # To print the shape

(205, 14)

In [9]:
df.info()  # To print the names & dataTypes of the columns

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student_ID         205 non-null    int64
 1   Name               205 non-null    str
 2   Age                205 non-null    object
 3   Gender             205 non-null    str
 4   City               205 non-null    str
 5   Department         205 non-null    str
 6   Education_Level    205 non-null    str
 7   Attendance_%       189 non-null    float64
 8   Study_Hours_Daily  200 non-null    float64
 9   Assignments        195 non-null    float64
 10  Quizzes            205 non-null    int64
 11  Midterm            195 non-null    float64
 12  Internet_Access    205 non-null    str
 13  Final_Score        205 non-null    int64
dtypes: float64(4), int64(3), object(1), str(6)
memory usage: 22.6+ KB

In [10]:
df.head(5) # To print the first five records of the dataframe

,Student_ID,Name,Age,Gender,City,Department,Education_Level,Attendance_%,Study_Hours_Daily,Assignments,Quizzes,Midterm,Internet_Access,Final_Score
0,1,Uzma,24,Female,Lahore,CS,Intermediate,60.0,7.0,6.0,13,89.0,No,53
1,2,ZAHID,19,female,Karachi,SE,Intermediate,82.0,4.0,NaN,5,84.0,Yes,55
2,3,Sara,19,Female,Lahore,BBA,Intermediate,NaN,5.0,10.0,9,50.0,Yes,42
3,4,Zahid,22,Male,Rawalpindi,EE,Intermediate,98.0,7.0,8.0,8,68.0,Yes,49
4,5,Zahid,21,Male,Karachi,SE,Intermediate,98.0,3.0,5.0,17,75.0,Yes,49

In [11]:
df.tail(5) # To print the last five records of the dataframe

,Student_ID,Name,Age,Gender,City,Department,Education_Level,Attendance_%,Study_Hours_Daily,Assignments,Quizzes,Midterm,Internet_Access,Final_Score
200,185,Waseem,23,Male,Karachi,SE,Intermediate,85.0,7.0,6.0,9,NaN,No,46
201,38,Ayesha,23,Male,Wah,CS,Intermediate,71.0,4.0,9.0,13,87.0,Yes,51
202,68,AYESHA,24,Male,Lahore,CS,Bachelors,70.0,4.0,5.0,5,NaN,No,40
203,180,Ali,25,MALE,Islamabad,EE,Intermediate,NaN,4.0,9.0,6,55.0,Yes,44
204,52,Ahmed,24,FEMALE,Wah,ME,Bachelors,60.0,3.0,8.0,10,53.0,Yes,40

In [12]:
df.describe() # .describe() for the statistical summary of the data

,Student_ID,Attendance_%,Study_Hours_Daily,Assignments,Quizzes,Midterm,Final_Score
count,205.000000,189.000000,200.000000,195.000000,205.000000,195.000000,205.000000
mean,100.600000,76.841270,4.190000,7.030769,11.395122,67.876923,46.819512
std,58.049303,15.771513,1.985854,1.950172,4.521731,15.100530,11.450302
min,1.000000,-10.000000,1.000000,4.000000,5.000000,40.000000,40.000000
25%,51.000000,66.000000,3.000000,5.000000,7.000000,55.000000,40.000000
50%,100.000000,79.000000,4.000000,7.000000,11.000000,67.000000,45.000000
75%,151.000000,87.000000,6.000000,9.000000,15.000000,80.000000,50.000000
max,200.000000,115.000000,7.000000,10.000000,19.000000,94.000000,150.000000

In [13]:
df.isnull().sum() # Checking the null values in the whole data

Student_ID            0
Name                  0
Age                   0
Gender                0
City                  0
Department            0
Education_Level       0
Attendance_%         16
Study_Hours_Daily     5
Assignments          10
Quizzes               0
Midterm              10
Internet_Access       0
Final_Score           0
dtype: int64

In [14]:
df['Gender'] = df['Gender'].str.title()
# Converting all the String values inside the Gender column into a title(Initial Capitalized) 
# and overwriting the result onto the same Gender column

In [15]:
df['Name'] = df['Name'].str.title()
# Converting all the String values inside the Name column into a title(Initial Capitalized) 
# and overwriting the result onto the same Name column

In [ ]:
df['Department'] = df['Department'].str.upper().str.strip()
# Converting all the abreviations of department names into upper case letters using the upper() method and 
# removing the surplus spaces using the strip() method. Both methods belong to String dataType

In [18]:
df['Age'] = pd.to_numeric(df['Age'], errors= 'coerce') 
# Converts the whole column to numeric, errors = coerce converts the invalid values into Null(NaN) 
# and overwriting the result onto the same Age column

df['Age'] = df['Age'].fillna(df['Age'].median())
# Filling all the null values of Age column with the median of the column.
# Why Median and not mean?
# Because the column has a lotta values missing(NUll) and as it is demand of the project, so we replace NaN with median not mean.

In [19]:
df['Attendance_%'] = df['Attendance_%'].mask((df['Attendance_%'] > 100) | (df['Attendance_%'] < 0), np.nan)
# Using the .mask() method to replace all the values which satisfy any(OR operator symbol pipe(|)) of the two conditions with NaN(NULL)

df['Attendance_%'] = df['Attendance_%'].fillna(df['Attendance_%'].median())
# Filling the null values with the median

In [20]:
df['Assignments'] = df['Assignments'].fillna(df['Assignments'].median())
# Filling the null values with the median

In [21]:
df['Study_Hours_Daily'] = df['Study_Hours_Daily'].fillna(df['Study_Hours_Daily'].median())
# Filling the null values with the median

In [22]:
df['Midterm'] = df['Midterm'].fillna(df['Midterm'].median())
# Filling the null values with the median

In [23]:
df['Final_Score'] = df['Final_Score'].mask((df['Final_Score'] > 100), np.nan)
# Using the .mask() method to replace all the values which satisfy condition with NaN(NULL)

df['Final_Score'] = df['Final_Score'].fillna(df['Final_Score'].median())
# Filling the null values with the median

In [29]:
df.drop_duplicates(inplace = True) # Dropping all the duplicates

In [30]:
print(df.isnull().sum()) # Final check to confirm the existence of a null value throughout the dataFrame

Student_ID           0
Name                 0
Age                  0
Gender               0
City                 0
Department           0
Education_Level      0
Attendance_%         0
Study_Hours_Daily    0
Assignments          0
Quizzes              0
Midterm              0
Internet_Access      0
Final_Score          0
dtype: int64

In [31]:
df.to_excel('../data/cleaned_student_performance_dataset.xlsx', index=False) # Exporting the cleaned data into an excel file